### ISSUE TITLE
can you clarify this?

### ISSUE THREAD

**Issue by lazymesh** [caroljmcdonald/mapr-streams-sparkstreaming-hbase#2]
I don't think val sqlContext = SQLContext.getOrCreate(rdd.sparkContext) should work in  mapr-streams-sparkstreaming-hbase/src/main/scala/solution/SensorStreamConsumer.scala
 file as I don't see any getOrCreate() api for SQLContext.

**Comment by caroljmcdonald** [comment]
https://spark.apache.org/docs/1.6.3/api/java/org/apache/spark/sql/SQLContext.html#getOrCreate(org.apache.spark.SparkContext)

spark 1.6

**Comment by caroljmcdonald** [comment]
for a more recent spark hbase example check out

https://github.com/caroljmcdonald/mapr-sparkml-streaming-uber/tree/master/src/main/scala/com/sparkkafka/uber

**Comment by lazymesh** [comment]
I never used 1.6 version of spark, so I didn't know about that. But is it really safe to create so many instances of sqlcontext?

**Comment by caroljmcdonald** [comment]
It gets it if already created 

-----Original Message-----

**Comment by lazymesh** [comment]
ok. that explains it. The api document says it too. Thanks for the clarification. I learned a new stuff. :)
